# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.srcs/sources_1/bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0.xci
# IP: The module: 'riscv_RocketChip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/init_sequence_rom/init_sequence_rom.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/pixel_buffer/pixel_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/charLib/charLib.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/charLib/charLib_ooc.xdc

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_RocketChip_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.srcs/sources_1/bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0.xci
# IP: The module: 'riscv_RocketChip_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/init_sequence_rom/init_sequence_rom.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==init_sequence_rom || ORIG_REF_NAME==init_sequence_rom} -quiet] -quiet

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/pixel_buffer/pixel_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pixel_buffer || ORIG_REF_NAME==pixel_buffer} -quiet] -quiet

# IP: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/charLib/charLib.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==charLib || ORIG_REF_NAME==charLib} -quiet] -quiet

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/init_sequence_rom/init_sequence_rom_ooc.xdc

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/pixel_buffer/pixel_buffer_ooc.xdc

# XDC: /home/lee/Downloads/Nexys-Video-GPIO/src/ip/charLib/charLib_ooc.xdc

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_RocketChip_0/riscv_RocketChip_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_RocketChip_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
