# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.srcs/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xci
# IP: The module: 'riscv_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.srcs/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xci
# IP: The module: 'riscv_util_ds_buf_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/lee/rebuild_oled_switch_cmd/vivado-risc-v/workspace/rocket64b1/vivado-genesys2-riscv/genesys2-riscv.gen/sources_1/bd/riscv/ip/riscv_util_ds_buf_0_0/riscv_util_ds_buf_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'riscv_util_ds_buf_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
